image: aictx/ci-python-arch:latest

before_script:
  - pip install --upgrade pip
  - pip install --upgrade --force-reinstall torch
  - pip install tensorflow==1.15
  - pip install . --no-cache-dir
  - pip install m2r

unittests:
  tags:
    - python
    - aiCTX

  script:
    - pytest

  only:
    - master


pages:
  tags:
    - python
    - aiCTX

  stage: deploy

  script:
    - cd docs
    - make html
    - mv build/html/ ../public/

  artifacts:
    paths:
    - public

  only:
    - master

dist_build:
  tags:
    - python
    - aiCTX

  stage: build

  only:
    - pip


  before_script:
    - pip install --upgrade pip
    - pip install wheel

  script:
    - python setup.py sdist bdist_wheel

  artifacts:
    paths:
      - dist

pypi_deploy:
  tags:
    - python
    - aiCTX
  
  stage: deploy
  when: manual

  only:
    - pip

  dependencies:
    - dist_build

  before_script:
    - pip install --upgrade pip
    - pip install --upgrade twine

  script:
          - python -m twine upload --repository-url https://test.pypi.org/legacy/ dist/*
